### PR TITLE
CB-9673 Fixed test spec.6 failure on iOS

### PR DESCRIPTION
**Pull request by alsorokin**
https://issues.apache.org/jira/browse/CB-9673

### CODE REVIEW

**Comment by daserge** [comment]
@alsorokin, is this ios behavior documented somewhere (so that we could add a link)?

**Comment by daserge** [comment]
Tested, works well.

**Comment by alsorokin** [comment]
I've added a couple of links describing this behavior to JIRA issue.

**Comment by daserge** [comment]
Thanks @alsorokin, that is great!

**Pull request closed without merging**
