### PR TITLE
CB-12107: (android) Trigger media scanner after downloading a file in…

### PR DESCRIPTION
**Pull request by beatgrabe**
### Platforms affected
Android

### What does this PR do?
Automatically triggers "ACTION_MEDIA_SCANNER_SCAN_FILE" broadcasting when a new file was downloadws into a public directory on android

### What testing has been done on this change?
- Code was tested on a real Nexus 4 device.
- npm test

### Checklist
- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change.

…to a public directory

### CODE REVIEW

**Comment by cordova-qa** [comment]
Cordova CI Build has one or more failures. Link: http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-file-transfer-pr/40/

 312 tests run, 26 skipped, 50 failed.

**Comment by infil00p** [comment]
@beatgrabe Can you send an empty commit to the branch so that we can re-bump the CI? I think it got broken during a past build unrelated to this one.  Thanks!

**Comment by cordova-qa** [comment]
Cordova CI Build has one or more failures. Link: http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-file-transfer-pr/43/

 312 tests run, 26 skipped, 50 failed.

**Comment by beatgrabe** [comment]
@infil00p Seems like project is still broken…

**Comment by infil00p** [comment]
@beatgrabe And the tests that are failing are all related to this plugin.  Until these pass, I'm not going to merge it in.

**Comment by beatgrabe** [comment]
@infil00p Alright…keep me updated

**Comment by alsorokin** [comment]
Let there be tests

**Comment by maverickmishra** [comment]
With the new features introduced in [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest), this plugin is not needed any more. Migrating from this plugin to using the new features of [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest), is explained in this [Cordova blog post](https://cordova.apache.org/blog/2017/10/18/from-filetransfer-to-xhr2.html).

**Pull request closed without merging**
