### PR TITLE
Updated README for Android file uploads.

### PR DESCRIPTION
**Pull request by shamilovtim**
### Platforms affected
Android

### What does this PR do?
Updates the README to address Android quirks with upload functionality. Saves people some time.

### What testing has been done on this change?
N/A

### CODE REVIEW

**Comment by shamilovtim** [comment]
I know the plugin is deprecated but in case anyone is still using it or intends to use it for whatever reason this little blurb in the README will save people a lot of time and trouble I think.

**Comment by janpio** [comment]
Can you provide some context? Is this true for all upload or just for some configuration? What happens if one doesn't set the option?

**Comment by shamilovtim** [comment]
Further research leads me to believe that this is an issue with Flask rather than Android. Closing

**Comment by janpio** [comment]
Thanks for following up, was suspecting something like this.

**Pull request closed without merging**
