### PR TITLE
CB-6503 allow file uploads to be sent directly, rather than only as multipart form data

### PR DESCRIPTION
**Pull request by machenmusik**

### CODE REVIEW

**Comment by LanceEa** [comment]
I'm trying to upload some images to Azure Blob Storage and it doesn't seem to like the multipart-form. I would like to be able to upload using "image/jpeg" o at least be able to keep it generic and leverage "application/octet-stream". 

Any status on this PR or changes coming to the file transfer plug-in?

Thanks!

**Comment by visum** [comment]
Bump. I'm in need of this as well. We still just waiting on @machenmusik to file an ICLA?

**Comment by riaan53** [comment]
+1

**Comment by machenmusik** [comment]
thought I did the ICLA a long while back... anyway, did it again

**Comment by ms88privat** [comment]
@clelland can you please merge it now?

**Comment by clelland** [comment]
@machenmusik, I definitely see the CLA now -- thanks!
And it's merged -- if there are any issues with it, please keep the bug at [CB-6503](https://issues.apache.org/jira/browse/CB-6503) updated.

**Pull request closed without merging**
