### PR TITLE
CB-9600 FileUploadOptions params not posted on iOS

### PR DESCRIPTION
**Pull request by daserge**
Documents supported params key/value type

[Jira issue](https://issues.apache.org/jira/browse/CB-9600)

### CODE REVIEW

**Comment by mirko77** [comment]
I am still having the issue using the plugin version 1.5 on iOS 9.2.1

POST request is empty, FILE is ok

**Comment by purplecabbage** [comment]
@mirko77 Please provide more details, and repro steps in JIRA 
[ https://issues.apache.org/jira/browse/CB-9600 ]
Where are you posting to? What kind of server is it? What is it getting?

**Comment by daserge** [comment]
App JS code with FileUploadOptions would be useful too.

**Comment by mirko77** [comment]
I am posting to a Linux server (Ubuntu 14.10), PHP 5.6 backend , from an Ionic1.2.4 app.

Here is the code, I removed the stuff not related to the bug

```

var uploader = new FileTransfer();
var options = new FileUploadOptions();
var upload_URL = $rootScope.serverUrl + PARAMETERS.API_PATH + '/upload/' + slug;
var file = $rootScope.file;
var file_URI;

function _onSuccess(r) {}

function _onError(error) {}

// Set options for multipart entity file
options.fileKey = 'name';
options.fileName = file.file_name;
options.params = {
  data: {
    entry_uuid: "3e6450ee-eb6e-5387-0ec7-da7d13c6df30",
    id: "3e6450ee-eb6e-5387-0ec7-da7d13c6df30",
    attributes: {
      form: {
        type: "hierarchy",
        ref: "b8906ef28f944a26a1b7839290a5c2a6_57078c27d0238"
      }
    },
    type: "file",
    relationships: {
      branch: {

      },
      parent: {

      }
    },
    file: {
      input_ref: "b8906ef28f944a26a1b7839290a5c2a6_57078c27d0238_57078cbf32c50",
      type: "photo",
      name: "3e6450ee-eb6e-5387-0ec7-da7d13c6df30_1460537677.jpg"
    }
  }
};

if (auth) {
  options.headers = {
    Authorization: 'Bearer ' + auth;
  };
}

file_URI = file.file_path + file.project_ref + '/' + file.file_name;

//append protocol for file on ios
if (window.device.platform === PARAMETERS.IOS) {
  file_URI = 'file://' + file_URI;
  options.chunkedMode = false;
}

uploader.upload(file_URI, upload_URL, _onSuccess, _onError, options);
```

content of the POST array of an Android request:

`Array([data] => {
  "entry_uuid": "3e6450ee-eb6e-5387-0ec7-da7d13c6df30",
  "id": "3e6450ee-eb6e-5387-0ec7-da7d13c6df30",
  "attributes": {
    "form": {
      "type": "hierarchy",
      "ref": "b8906ef28f944a26a1b7839290a5c2a6_57078c27d0238"
    }
  },
  "type": "file",
  "relationships": {
    "branch": {},
    "parent": {}
  },
  "file": {
    "input_ref": "b8906ef28f944a26a1b7839290a5c2a6_57078c27d0238_57078cbf32c50",
    "type": "photo",
    "name": "3e6450ee-eb6e-5387-0ec7-da7d13c6df30_1460537677.jpg"
  }
})`

content of the POST array of an iOS request:

`Array
()
`

**Comment by daserge** [comment]
`params` should be `A set of optional key/value pairs to pass in the HTTP request. (Object, key/value - DOMString)` as the documentation says - can you please try to JSON.stringify the `data` object?

**Comment by mirko77** [comment]
@daserge fair enough, I think we will have to simplify that object. It has always been working on Android so we never faced the issue. Stringifying or serialising the data object work

**Pull request merged**
