### PR TITLE
CB-11067 - Adds content-length to multipart string if file length determined as also iOS plugin does

### PR DESCRIPTION
**Pull request by oddcb**
ICLA signed and sent per email.

https://issues.apache.org/jira/browse/CB-11067

### CODE REVIEW

**Comment by nikhilkh** [comment]
@daserge  to help review. Looks like we might need some tests for this as well.

**Comment by cordova-qa** [comment]
Cordova CI Build has one or more failures. 

**Commit**     - [Link](https://github.com/apache/cordova-plugin-file-transfer/pull/140/commits/7673590ad65a673c7578f7eead78fd4bd083f05c)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-file-transfer-pr/5/)

| Builder Name  | Console Output | Test Report | Device Logs  |
|     :---:     |     :---:      |   :---:     |     :---:    |
| [Windows 8.1 Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-file-transfer-pr/5//label=windows-slave,platformName=windows-8.1-store/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-file-transfer-pr/5//label=windows-slave,platformName=windows-8.1-store/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-file-transfer-pr/5//label=windows-slave,platformName=windows-8.1-store/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-file-transfer-pr/5//label=windows-slave,platformName=windows-8.1-store/artifact/) |
| [Windows 10  Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-file-transfer-pr/5//label=windows-slave,platformName=windows-10-store/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-file-transfer-pr/5//label=windows-slave,platformName=windows-10-store/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-file-transfer-pr/5//label=windows-slave,platformName=windows-10-store/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-file-transfer-pr/5//label=windows-slave,platformName=windows-10-store/artifact/) |
| [Windows 8.1 Phone]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-file-transfer-pr/5//label=windows-slave,platformName=windows-8.1-phone/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-file-transfer-pr/5//label=windows-slave,platformName=windows-8.1-phone/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-file-transfer-pr/5//label=windows-slave,platformName=windows-8.1-phone/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-file-transfer-pr/5//label=windows-slave,platformName=windows-8.1-phone/artifact/) |
| [iOS]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-file-transfer-pr/5//label=mac-slave,platformName=ios/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-file-transfer-pr/5//label=mac-slave,platformName=ios/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-file-transfer-pr/5//label=mac-slave,platformName=ios/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-file-transfer-pr/5//label=mac-slave,platformName=ios/artifact/) |
| [Android Mac]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-file-transfer-pr/5//label=mac-slave,platformName=android/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-file-transfer-pr/5//label=mac-slave,platformName=android/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-file-transfer-pr/5//label=mac-slave,platformName=android/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-file-transfer-pr/5//label=mac-slave,platformName=android/artifact/) |

**Comment by daserge** [comment]
@oddcb, thanks for the contribution!
This is not an issue though as the `Content-Length` header is set by [`setFixedLengthStreamingMode`](https://developer.android.com/reference/java/net/HttpURLConnection.html?hl=ru#setFixedLengthStreamingMode%28int%29) in https://github.com/apache/cordova-plugin-file-transfer/blob/9347606dd33fe07ea36799b4dd28804019c68835/src/android/FileTransfer.java#L438.
I've recently added [tests](https://github.com/apache/cordova-plugin-file-transfer/commit/9347606dd33fe07ea36799b4dd28804019c68835#diff-2a8a5fef3397df87ab538f028a5c6b50R1494) verifying `Content-Length`, `Content-Type` and `Transfer-Encoding` for multipart/non-multipart & chunked/non-chunked modes - and they are passing for Android and iOS.

**Comment by oddcb** [comment]
Thanks for you reply @daserge 

So I'm not very into how file uploads are done properly, but the problem I fixed for our api here was adding the Content-Length into the code block starting at: 

https://github.com/apache/cordova-plugin-file-transfer/blob/9347606dd33fe07ea36799b4dd28804019c68835/src/android/FileTransfer.java#L406

Result:

```java
 
                    beforeData.append(LINE_START).append(BOUNDARY).append(LINE_END);
                    beforeData.append("Content-Disposition: form-data; name=\"").append(fileKey).append("\";");
                    beforeData.append(" filename=\"").append(fileName).append('"').append(LINE_END);

                    if(filesize > -1)
                        beforeData.append("Content-Length: ").append(filesize).append(LINE_END);

                    beforeData.append("Content-Type: ").append(mimeType).append(LINE_END).append(LINE_END);
                    byte[] beforeDataBytes = beforeData.toString().getBytes("UTF-8");
                    byte[] tailParamsBytes = (LINE_END + LINE_START + BOUNDARY + LINE_START + LINE_END).getBytes("UTF-8");
                    int stringLength = beforeDataBytes.length + tailParamsBytes.length;
```

As far as I can tell it is also what happens for iOS in https://github.com/apache/cordova-plugin-file-transfer/blob/9347606dd33fe07ea36799b4dd28804019c68835/src/ios/CDVFileTransfer.m#L222

``` [postBodyBeforeFile appendData:[[NSString stringWithFormat:@"Content-Length: %ld\r\n\r\n", (long)[fileData length]] dataUsingEncoding:NSUTF8StringEncoding]];```

History for us is just that our ios app was working with the file upload plugin as is, but when we added the android app with the plugin it did not send Content-Length as iOS did and hence our file upload API started to scream. We are using Jersey in our backend.

As far as I can tell your opinion is that this added code should not be required interacting with a standard api?

**Comment by daserge** [comment]
@oddcb, yes, `Content-Length` should be added by `setFixedLengthStreamingMode`.
Which Android OS version had the issue?
Could you try it again with the master plugin version?
Do you use chunked mode for requests (Content-Length should not be present in case of chunked mode)?

**Comment by vladimir-kotikov** [comment]
@oddcb, any updates? Is this still actual? If not, please close this PR

**Comment by oddcb** [comment]
We've changed our server side to retrieve content-size as I realize it should be. Closing this.

**Pull request closed without merging**
