### PR TITLE
CB-12809 android

### PR DESCRIPTION
**Pull request by amovsesy**
Fixing a security issue which is banned by google play that can be found https://support.google.com/faqs/answer/6346016

Adding a check for the certificate that comes in when connecting to the server

### Platforms affected
Android

### What does this PR do?
Adds a check for the connection that gets created

### What testing has been done on this change?
Ran the tests

### Checklist
- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [x] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by amovsesy** [comment]
@stevengill Can you please take a look at this

**Comment by cordova-qa** [comment]
Cordova CI Build has completed successfully.

**Commit**     - [Link](https://github.com/apache/cordova-plugin-file-transfer/pull/179/commits/35886fe8ecce12f1932f5eec4b614b2eebd6d5e3)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-file-transfer-pr/78/)

 318 tests run, 15 skipped, 0 failed.

**Comment by amovsesy** [comment]
@jcesarmobile, I understand, but this is violating Google's play ToS and it clearly states that any new updates or apps using an unsafe implementation of TrustManager will be blocked. https://support.google.com/faqs/answer/6346016. Given that, any apps using this code would be in violation and could be blocked from the google store.

**Comment by jcesarmobile** [comment]
Yeah, so the solution should be to deprecate `trustAllHosts`, documenting it and then remove those methods, not to implement them with a safe implementation because that will make `trustAllHosts` to stop working

**Comment by filmaj** [comment]
+1 to @jcesarmobile's proposed solution.

**Comment by kerrishotts** [comment]
+1 to deprecation as well.

**Pull request closed without merging**
