### PR TITLE
patch method

### PR DESCRIPTION
**Pull request by theromis**
We using Django Rest Framework, and it sending partial updates as a PATCH method. So the *patch* **SHOULD** be at list an option for this module.

### CODE REVIEW

**Comment by cordova-qa** [comment]
Cordova CI Build has one or more failures. Link: http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-file-transfer-pr/44/

 260 tests run, 24 skipped, 34 failed.

**Comment by theromis** [comment]
@shazron can somebody take care of this PR?

**Comment by marcpursals** [comment]
Hi, I'm really interested on using patch method. Is the brach enough stable to use it? Is there any scheduled time to get this functionality available on stable version?

Thanks in advance

**Comment by theromis** [comment]
@daserge @matrosov-nikita @alsorokin Can somebody take care of this PR?

**Comment by marcpursals** [comment]
Actually I did clone this branch and I'm using it. It works like a charm. So I'm freezing for next stable release. God job @theromis thanks.

**Comment by purplecabbage** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH
LGTM!

**Comment by shazron** [comment]
This patch (pun, I know) needs a README update for `httpMethod` as well, to be complete.

**Comment by maverickmishra** [comment]
With the new features introduced in [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest), this plugin is not needed any more. Migrating from this plugin to using the new features of [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest), is explained in this [Cordova blog post](https://cordova.apache.org/blog/2017/10/18/from-filetransfer-to-xhr2.html).

**Pull request closed without merging**
