### PR TITLE
CB-12847: added `bugs` entry to package.json.

### PR DESCRIPTION
**Pull request by filmaj**
### What does this PR do?

Adds a bugs entry to the package.json.

### What testing has been done on this change?

None.

### Checklist
- [X] Issue reported: [CB-12847](https://issues.apache.org/jira/browse/CB-12847)
- [X] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by cordova-qa** [comment]
Cordova CI Build has one or more failures. 

**Commit**     - [Link](https://github.com/apache/cordova-plugin-file-transfer/pull/180/commits/0f639f91b85f50f62c2b788bb20d537ab2c5e894)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-file-transfer-pr/79/)

 318 tests run, 15 skipped, 2 failed.

**Comment by filmaj** [comment]
Let there be tests

**Comment by cordova-qa** [comment]
Cordova CI Build has one or more failures. 

**Commit**     - [Link](https://github.com/apache/cordova-plugin-file-transfer/pull/180/commits/21f019472de74df7f266dcb21e18b3e294e35ee3)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-file-transfer-pr/80/)

 318 tests run, 15 skipped, 4 failed.

**Comment by alsorokin** [comment]
These flaky failures are clearly not caused by tour changes. I see them in the periodic build too.

**Comment by cordova-qa** [comment]
Cordova CI Build has one or more failures. 

**Commit**     - [Link](https://github.com/apache/cordova-plugin-file-transfer/pull/180/commits/f6621c59230caaef2f8f2ef55d176bfb5f550be8)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-file-transfer-pr/81/)

 318 tests run, 15 skipped, 2 failed.

**Pull request merged**
