### PR TITLE
[windows] added supprt for cdvfile://

### PR DESCRIPTION
**Pull request by biodiv**
Added support for cdvfile:// paths

### CODE REVIEW

**Comment by starquake** [comment]
Would like to see this merged. Right now this plugin doesn't work on Windows.

**Comment by nikhilkh** [comment]
Can you please file a JIRA for this here - https://issues.apache.org/jira/ describing the scenario that fails?

**Comment by biodiv** [comment]
I created the issue as I could not find it yet. https://issues.apache.org/jira/browse/CB-8816
The problem occurs when using toInternalURL() on windows which gives us cdvfile://.

**Comment by sgrebnov** [comment]
tested and merged to master

**Pull request closed without merging**
